---
- name: Auto iDRAC Configuration
  hosts: IDRACSVRS
  become: no
  gather_facts: no
  tasks:
     - name: get physical disk info
       raw: racadm storage get pdisks -o
       register: out
     - debug: var=out.stdout_lines
     - name: get virtual disk raid info
       raw: racadm storage get vdisks -o
       register: out
     - debug: var=out.stdout_lines
     - name: get server boot mode
       raw: racadm get BIOS.BiosBootSettings
       register: out
     - debug: var=out.stdout_lines
